import pino, { type LoggerOptions } from "pino";

export type { Logger } from "pino";

const redactionPaths = [
  "req.headers.authorization",
  "req.headers.cookie",
  "request.headers.authorization",
  "request.headers.cookie",
  "headers.authorization",
  "headers.cookie",
  "err.message",
  "err.stack",
  "error.message",
  "error.stack",
  "apiKey",
  "token",
  "secret",
  "password",
  "signedUrl",
  "credential",
  "serviceRoleKey",
  "secretAccessKey",
  "databaseUrl",
  "hatchetToken",
  "SUPABASE_SERVICE_ROLE_KEY",
  "CREDENTIAL_MASTER_KEY",
  "HATCHET_CLIENT_TOKEN",
  "BUSINESS_DATABASE_URL",
  "BUSINESS_DATABASE_MIGRATION_URL",
  "BUSINESS_DATABASE_LISTENER_URL",
  "S3_SECRET_ACCESS_KEY",
  "METRICS_BEARER_TOKEN",
  "*.apiKey",
  "*.token",
  "*.secret",
  "*.password",
  "*.signedUrl",
  "*.credential",
  "*.serviceRoleKey",
  "*.secretAccessKey",
  "*.databaseUrl",
  "*.hatchetToken",
  "*.SUPABASE_SERVICE_ROLE_KEY",
  "*.CREDENTIAL_MASTER_KEY",
  "*.HATCHET_CLIENT_TOKEN",
  "*.BUSINESS_DATABASE_URL",
  "*.BUSINESS_DATABASE_MIGRATION_URL",
  "*.BUSINESS_DATABASE_LISTENER_URL",
  "*.S3_SECRET_ACCESS_KEY",
  "*.METRICS_BEARER_TOKEN",
  "*.err.message",
  "*.err.stack",
  "*.error.message",
  "*.error.stack",
];

export function createLogger(service: string, level = process.env.LOG_LEVEL ?? "info", destination?: pino.DestinationStream) {
  const options: LoggerOptions = {
    name: service,
    level,
    redact: { paths: redactionPaths, censor: "[REDACTED]" },
    base: { service },
  };
  return destination ? pino(options, destination) : pino(options);
}
