import { z } from "zod";

export const apiErrorCodeSchema = z.enum([
  "authentication_required",
  "invalid_access_token",
  "account_disabled",
  "account_auth_sync_failed",
  "admin_self_disable_forbidden",
  "last_admin_disable_forbidden",
  "user_not_found",
  "admin_required",
  "workspace_access_forbidden",
  "workspace_write_forbidden",
  "forbidden",
  "feature_disabled",
  "validation_failed",
  "invalid_request",
  "invalid_server_response",
  "internal_error",
  "idempotency_key_required",
  "invalid_idempotency_key",
  "idempotency_conflict",
  "idempotency_key_conflict",
  "idempotency_request_failed",
  "project_version_conflict",
  "project_not_found",
  "project_target_conflict",
  "insufficient_credits",
  "job_not_retryable",
  "job_not_cancelable",
  "generation_batch_not_found",
  "generation_job_not_found",
  "generation_job_not_retryable",
  "generation_attempt_not_found",
  "generation_attempt_not_unknown",
  "model_unavailable_or_unpriced",
  "asset_not_found",
  "asset_too_large",
  "asset_upload_incomplete",
  "asset_verification_in_progress",
  "asset_upload_rejected",
  "asset_state_conflict",
  "asset_size_mismatch",
  "asset_mime_mismatch",
  "asset_checksum_mismatch",
  "asset_signature_mismatch",
  "asset_decode_failed",
  "media_probe_unavailable",
  "reference_asset_unavailable",
  "import_file_required",
  "invalid_import_media_type",
  "import_too_large",
  "import_capacity_exceeded",
  "invalid_import_archive",
  "import_id_conflict",
  "import_not_found",
  "large_debit_confirmation_required",
  "wallet_adjustment_rejected",
  "provider_url_unresolvable",
  "provider_url_rejected",
  "provider_channel_not_found",
  "provider_channel_incompatible",
  "content_moderation_rejected",
  "provider_parameter_rejected",
  "provider_authentication_failed",
  "provider_rate_limited_not_accepted",
  "provider_unavailable_not_accepted",
  "provider_outcome_unknown",
  "provider_task_failed",
  "provider_task_expired",
  "media_download_failed",
  "media_type_rejected",
  "media_source_rejected",
  "object_storage_failed",
  "dispatch_unavailable",
  "workflow_contract_unsupported",
  "data_invariant_violation",
]);

export const apiErrorSchema = z.object({
  code: apiErrorCodeSchema,
  message: z.string().min(1).max(500),
  retryable: z.boolean(),
  correlationId: z.string().min(1).max(128),
  details: z.record(z.string(), z.unknown()).optional(),
});

export const apiErrorEnvelopeSchema = z.object({ error: apiErrorSchema });
export const providerAcceptanceSchema = z.enum(["not_accepted", "accepted", "unknown"]);

export type ApiErrorCode = z.infer<typeof apiErrorCodeSchema>;
export type ApiError = z.infer<typeof apiErrorSchema>;
export type ApiErrorEnvelope = z.infer<typeof apiErrorEnvelopeSchema>;
export type ProviderAcceptance = z.infer<typeof providerAcceptanceSchema>;
