DROP SCHEMA IF EXISTS app CASCADE;

DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS platform_risk_entries CASCADE;
DROP TABLE IF EXISTS import_source_mappings CASCADE;
DROP TABLE IF EXISTS imports CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;
DROP TABLE IF EXISTS generation_job_events CASCADE;
DROP TABLE IF EXISTS wallet_entries CASCADE;
DROP TABLE IF EXISTS credit_reservations CASCADE;
DROP TABLE IF EXISTS generation_job_targets CASCADE;
DROP TABLE IF EXISTS generation_capacity_rate_windows CASCADE;
DROP TABLE IF EXISTS provider_channel_capacity_leases CASCADE;
DROP TABLE IF EXISTS generation_attempts CASCADE;
DROP TABLE IF EXISTS generation_jobs CASCADE;
DROP TABLE IF EXISTS generation_batches CASCADE;
DROP TABLE IF EXISTS platform_idempotency_requests CASCADE;
DROP TABLE IF EXISTS idempotency_requests CASCADE;
DROP TABLE IF EXISTS wallet_accounts CASCADE;
DROP TABLE IF EXISTS model_prices CASCADE;
DROP TABLE IF EXISTS model_configs CASCADE;
DROP TABLE IF EXISTS provider_channel_capacity_policies CASCADE;
DROP TABLE IF EXISTS provider_credentials CASCADE;
DROP TABLE IF EXISTS provider_channels CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS project_versions CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS workspace_members CASCADE;
DROP TABLE IF EXISTS workspaces CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

DROP TYPE IF EXISTS import_status;
DROP TYPE IF EXISTS idempotency_status;
DROP TYPE IF EXISTS outbox_status;
DROP TYPE IF EXISTS reservation_status;
DROP TYPE IF EXISTS model_status;
DROP TYPE IF EXISTS credential_status;
DROP TYPE IF EXISTS channel_status;
DROP TYPE IF EXISTS asset_kind;
DROP TYPE IF EXISTS asset_status;
DROP TYPE IF EXISTS attempt_status;
DROP TYPE IF EXISTS job_status;
DROP TYPE IF EXISTS batch_status;
DROP TYPE IF EXISTS generation_capability;
DROP TYPE IF EXISTS member_status;
DROP TYPE IF EXISTS workspace_role;
DROP TYPE IF EXISTS workspace_status;
DROP TYPE IF EXISTS platform_role;
DROP TYPE IF EXISTS profile_status;
